// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebToTest.Data;

namespace WebToTest.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("WebToTest.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "8546 Bliss Terrace ",
                            City = "San Anselmo",
                            DateOfBirth = new DateTime(1989, 8, 2, 14, 49, 9, 0, DateTimeKind.Unspecified),
                            Email = "Courtney.Miller@telus.net",
                            FirstName = "Tiffany",
                            LastName = "Iginla",
                            State = "Minnesota",
                            Telephone = "craft"
                        },
                        new
                        {
                            Id = 2,
                            Address = "7351 Rodney Street ",
                            City = "Newburgh",
                            DateOfBirth = new DateTime(2012, 7, 3, 6, 43, 40, 0, DateTimeKind.Unspecified),
                            Email = "Lucas.Cox@gmail.com",
                            FirstName = "Hunter",
                            LastName = "Sanchez",
                            State = "Virginia",
                            Telephone = "carles"
                        },
                        new
                        {
                            Id = 3,
                            Address = "2373 Bowne Street ",
                            City = "Amqui",
                            DateOfBirth = new DateTime(1930, 5, 19, 20, 33, 24, 0, DateTimeKind.Unspecified),
                            Email = "Mia.Gomes@shaw.ca",
                            FirstName = "Cary",
                            LastName = "Wilson",
                            State = "North Dakota",
                            Telephone = "government"
                        },
                        new
                        {
                            Id = 4,
                            Address = "5562 Wallaston Court ",
                            City = "Dimmitt",
                            DateOfBirth = new DateTime(2017, 6, 28, 22, 31, 10, 0, DateTimeKind.Unspecified),
                            Email = "Riley.Nelson@gmail.com",
                            FirstName = "Isabel",
                            LastName = "Price",
                            State = "Hawaii",
                            Telephone = "carles"
                        },
                        new
                        {
                            Id = 5,
                            Address = "7386 Lamont Court ",
                            City = "Brackettville",
                            DateOfBirth = new DateTime(1927, 3, 27, 0, 11, 17, 0, DateTimeKind.Unspecified),
                            Email = "Adam.Pearson@telus.net",
                            FirstName = "Nicholas",
                            LastName = "Kelly",
                            State = "Alabama",
                            Telephone = "freegan"
                        },
                        new
                        {
                            Id = 6,
                            Address = "6514 Rutland Road ",
                            City = "Eagle Lake",
                            DateOfBirth = new DateTime(1940, 3, 10, 21, 31, 58, 0, DateTimeKind.Unspecified),
                            Email = "Shelby.Rodriguez@rogers.ca",
                            FirstName = "Nicole",
                            LastName = "Yarobi",
                            State = "Kentucky",
                            Telephone = "life"
                        },
                        new
                        {
                            Id = 7,
                            Address = "4175 Kane Place ",
                            City = "Sainte-Anne-de-Bellevue",
                            DateOfBirth = new DateTime(2015, 6, 15, 6, 37, 17, 0, DateTimeKind.Unspecified),
                            Email = "Gabriella.Reed@microsoft.com",
                            FirstName = "Jake",
                            LastName = "Pitt",
                            State = "New York",
                            Telephone = "out"
                        },
                        new
                        {
                            Id = 8,
                            Address = "2984 Eastern Parkway ",
                            City = "Oak Grove",
                            DateOfBirth = new DateTime(1922, 4, 6, 13, 38, 48, 0, DateTimeKind.Unspecified),
                            Email = "Kaylee.Johnson@live.com",
                            FirstName = "Kaycee",
                            LastName = "Brooks",
                            State = "Delaware",
                            Telephone = "authentic"
                        },
                        new
                        {
                            Id = 9,
                            Address = "2423 Fane Court ",
                            City = "Coronado",
                            DateOfBirth = new DateTime(1919, 7, 4, 14, 2, 56, 0, DateTimeKind.Unspecified),
                            Email = "Sophia.Long@telus.net",
                            FirstName = "Ariana",
                            LastName = "Scott",
                            State = "Florida",
                            Telephone = "future"
                        },
                        new
                        {
                            Id = 10,
                            Address = "9103 Avenue A  ",
                            City = "Wallis",
                            DateOfBirth = new DateTime(1967, 11, 22, 3, 13, 56, 0, DateTimeKind.Unspecified),
                            Email = "John.Hall@att.com",
                            FirstName = "Jerica",
                            LastName = "Carter",
                            State = "Nebraska",
                            Telephone = "of"
                        },
                        new
                        {
                            Id = 11,
                            Address = "2932 Ebony Court ",
                            City = "La Tuque",
                            DateOfBirth = new DateTime(1939, 10, 4, 6, 50, 54, 0, DateTimeKind.Unspecified),
                            Email = "Ashley.Brown@gmail.com",
                            FirstName = "Jacqueline",
                            LastName = "Henderson",
                            State = "Minnesota",
                            Telephone = "pack"
                        },
                        new
                        {
                            Id = 12,
                            Address = "6456 9th Avenue ",
                            City = "Shady Shores",
                            DateOfBirth = new DateTime(1992, 3, 10, 22, 55, 32, 0, DateTimeKind.Unspecified),
                            Email = "Terica.Ramirez@rogers.ca",
                            FirstName = "Nathaniel",
                            LastName = "Scott",
                            State = "Nevada",
                            Telephone = "small"
                        },
                        new
                        {
                            Id = 13,
                            Address = "8896 Park Cir ",
                            City = "Hawkins",
                            DateOfBirth = new DateTime(1907, 1, 29, 22, 36, 23, 0, DateTimeKind.Unspecified),
                            Email = "Luis.Lewis@live.com",
                            FirstName = "Taylor",
                            LastName = "Cooper",
                            State = "Alabama",
                            Telephone = "week"
                        },
                        new
                        {
                            Id = 14,
                            Address = "4267 Union Avenue ",
                            City = "Point Arena",
                            DateOfBirth = new DateTime(1959, 7, 23, 13, 57, 31, 0, DateTimeKind.Unspecified),
                            Email = "Andrea.MacKenzie@microsoft.com",
                            FirstName = "Sierra",
                            LastName = "Powell",
                            State = "North Dakota",
                            Telephone = "you"
                        },
                        new
                        {
                            Id = 15,
                            Address = "1466 Brighton 5th Lane ",
                            City = "Laval",
                            DateOfBirth = new DateTime(1913, 9, 2, 14, 3, 39, 0, DateTimeKind.Unspecified),
                            Email = "Lucas.Barnes@shaw.ca",
                            FirstName = "Joshua",
                            LastName = "Martinez",
                            State = "Delaware",
                            Telephone = "freegan"
                        },
                        new
                        {
                            Id = 16,
                            Address = "2012 57th Street ",
                            City = "Fort Davis",
                            DateOfBirth = new DateTime(1951, 6, 8, 5, 10, 40, 0, DateTimeKind.Unspecified),
                            Email = "Kimberly.Gray@telus.net",
                            FirstName = "Sierra",
                            LastName = "Ross",
                            State = "Nebraska",
                            Telephone = "terry"
                        },
                        new
                        {
                            Id = 17,
                            Address = "2272 Keen Court ",
                            City = "Garden Hills",
                            DateOfBirth = new DateTime(1978, 6, 13, 14, 21, 27, 0, DateTimeKind.Unspecified),
                            Email = "Jordan.Davis@microsoft.com",
                            FirstName = "Angel",
                            LastName = "Wilson",
                            State = "Colorado",
                            Telephone = "Lo-fi"
                        },
                        new
                        {
                            Id = 18,
                            Address = "2180 Blake Court ",
                            City = "Hart",
                            DateOfBirth = new DateTime(1985, 5, 27, 0, 27, 57, 0, DateTimeKind.Unspecified),
                            Email = "Mia.Coleman@microsoft.com",
                            FirstName = "Hunter",
                            LastName = "Russell",
                            State = "Pennsylvania",
                            Telephone = "place"
                        },
                        new
                        {
                            Id = 19,
                            Address = "9574 Henry Street ",
                            City = "Desbiens",
                            DateOfBirth = new DateTime(1914, 8, 9, 18, 42, 34, 0, DateTimeKind.Unspecified),
                            Email = "Nathaniel.Green@gmail.com",
                            FirstName = "Madeline",
                            LastName = "Taylor",
                            State = "Ohio",
                            Telephone = "locavore"
                        },
                        new
                        {
                            Id = 20,
                            Address = "8002 Elliott Walk ",
                            City = "Truckee",
                            DateOfBirth = new DateTime(2004, 9, 22, 21, 31, 28, 0, DateTimeKind.Unspecified),
                            Email = "Benjamin.Phillips@gmx.com",
                            FirstName = "Aaliyah",
                            LastName = "Foster",
                            State = "Montana",
                            Telephone = "park"
                        },
                        new
                        {
                            Id = 21,
                            Address = "4472 Plumb 1st Street ",
                            City = "Parker",
                            DateOfBirth = new DateTime(1945, 3, 10, 22, 44, 14, 0, DateTimeKind.Unspecified),
                            Email = "Alejandro.Richardson@gmail.com",
                            FirstName = "Vanessa",
                            LastName = "Price",
                            State = "Iowa",
                            Telephone = "PBR"
                        },
                        new
                        {
                            Id = 22,
                            Address = "7751 Taaffe Place ",
                            City = "Citrus City",
                            DateOfBirth = new DateTime(1972, 11, 22, 21, 43, 41, 0, DateTimeKind.Unspecified),
                            Email = "Sydney.Brugger@gmx.com",
                            FirstName = "Benjamin",
                            LastName = "Hall",
                            State = "Georgia",
                            Telephone = "bicycle"
                        },
                        new
                        {
                            Id = 23,
                            Address = "4922 Seagate Avenue ",
                            City = "Shiner",
                            DateOfBirth = new DateTime(1960, 3, 3, 19, 57, 45, 0, DateTimeKind.Unspecified),
                            Email = "Alexandra.Morris@gmail.com",
                            FirstName = "Rosalinda",
                            LastName = "Hernandez",
                            State = "Idaho",
                            Telephone = "them"
                        },
                        new
                        {
                            Id = 24,
                            Address = "7419 Stewart Street ",
                            City = "Coronado",
                            DateOfBirth = new DateTime(1971, 12, 1, 15, 28, 40, 0, DateTimeKind.Unspecified),
                            Email = "Miguel.Carter@microsoft.com",
                            FirstName = "Isaac",
                            LastName = "Price",
                            State = "Idaho",
                            Telephone = "Tofu"
                        },
                        new
                        {
                            Id = 25,
                            Address = "3662 56th Drive ",
                            City = "Winnipeg Beach",
                            DateOfBirth = new DateTime(1946, 8, 5, 11, 13, 4, 0, DateTimeKind.Unspecified),
                            Email = "Elijah.Turner@hotmail.com",
                            FirstName = "Rebecca",
                            LastName = "Perry",
                            State = "Louisiana",
                            Telephone = "shorts"
                        },
                        new
                        {
                            Id = 26,
                            Address = "7175 Harbor View Terrace ",
                            City = "Roberval",
                            DateOfBirth = new DateTime(1906, 4, 13, 3, 3, 12, 0, DateTimeKind.Unspecified),
                            Email = "Grace.Flores@att.com",
                            FirstName = "Michael",
                            LastName = "Long",
                            State = "Illinois",
                            Telephone = "life"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
